name: Build and push Docker image

on:
  push:
    branches:
      'master'

env:
  REGISTRY: meltoz
  IMAGE_NAME: garage_api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuration du Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest .

      # Connexion au registre Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.REGISTRY}}
          password: ${{secrets.PASS_DOCKER}}

      # Pousser l'image Docker vers le registre
      - name: Push Docker image
        run: docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
